---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: main
          image: {{ .Values.docker.image.repo }}/{{ .Values.docker.image.name }}:{{ .Values.docker.image.tag }}
          env:
          - name: REDIS_ADDR
            value: {{ .Values.redis_addr }}
          imagePullPolicy: Never
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi

