apiVersion: v2
name: main
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: redis
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: 19.3.0
  - name: cadvisor
    repository: "https://ckotzbauer.github.io/helm-charts"
    version: 2.3.3
  - name: prometheus
    repository: "https://prometheus-community.github.io/helm-charts"
    version: 25.21.0
  - name: grafana
    repository: "https://grafana.github.io/helm-charts"
    version: 7.3.11